# Generated by Django 5.2.15 on 2026-07-14 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('tipo', models.CharField(choices=[('campeonato', 'Campeonato (amador/juvenil)'), ('junior_xp', 'Junior XP'), ('squashe', 'SquaSHE'), ('liga', 'FPS League'), ('outro', 'Outro')], default='campeonato', max_length=12, verbose_name='tipo')),
                ('tier', models.CharField(blank=True, max_length=20, verbose_name='tier')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['data_inicio', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('resumo', models.TextField(blank=True, verbose_name='resumo')),
                ('status', models.CharField(choices=[('ideia', 'Ideia'), ('planejamento', 'Planejamento'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('pausado', 'Pausado')], default='planejamento', max_length=14, verbose_name='status')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'tema',
                'verbose_name_plural': 'temas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RespostaProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('pergunta', models.CharField(max_length=255, verbose_name='pergunta')),
                ('resposta', models.TextField(blank=True, verbose_name='resposta')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='tarefas.projeto')),
            ],
            options={
                'verbose_name': 'resposta do projeto',
                'verbose_name_plural': 'business plan',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('tipo', models.CharField(choices=[('evento', 'Evento'), ('projeto', 'Projeto'), ('geral', 'Geral / recorrente'), ('reuniao', 'Reunião'), ('avulsa', 'Avulsa')], default='avulsa', max_length=10, verbose_name='tipo')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='hora')),
                ('feita', models.BooleanField(default=False, verbose_name='feita')),
                ('serie', models.CharField(blank=True, help_text='marca tarefas recorrentes/geradas (ex.: folha, reuniao-fps)', max_length=40, verbose_name='série')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='tarefas.evento')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='tarefas.projeto')),
                ('responsaveis', models.ManyToManyField(blank=True, related_name='tarefas', to='tarefas.pessoa')),
                ('temas', models.ManyToManyField(blank=True, related_name='tarefas', to='tarefas.tema')),
            ],
            options={
                'verbose_name': 'tarefa',
                'verbose_name_plural': 'tarefas',
                'ordering': ['feita', 'prazo', 'ordem', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ModeloTarefaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.CharField(choices=[('campeonato', 'Campeonato (amador/juvenil)'), ('junior_squashe', 'Junior XP / SquaSHE')], default='campeonato', max_length=16, verbose_name='checklist')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('offset_dias', models.IntegerField(default=0, help_text='negativo = dias antes do início; positivo = dias após o fim', verbose_name='offset (dias)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarefas.tema')),
            ],
            options={
                'verbose_name': 'tarefa padrão de evento',
                'verbose_name_plural': 'checklist padrão de evento',
                'ordering': ['checklist', 'ordem', 'id'],
            },
        ),
    ]
