# Generated by Django 5.2.15 on 2026-07-03 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='fim')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['data_inicio', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ModeloTarefaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('dias_antes', models.IntegerField(default=0, help_text='o prazo da tarefa = data do evento menos estes dias', verbose_name='prazo (dias antes do evento)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('responsavel_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarefas.pessoa', verbose_name='responsável padrão')),
            ],
            options={
                'verbose_name': 'tarefa padrão de evento',
                'verbose_name_plural': 'checklist padrão de evento',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('feita', models.BooleanField(default=False, verbose_name='feita')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='tarefas.evento')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='tarefas.projeto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='tarefas.pessoa', verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'tarefa',
                'verbose_name_plural': 'tarefas',
                'ordering': ['feita', 'prazo', 'ordem', '-id'],
            },
        ),
    ]
