# Generated by Django 5.2.15 on 2026-07-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='inscricoes_ate',
            field=models.DateField(blank=True, help_text='encerramento das inscrições — gera os avisos de fim de inscrição', null=True, verbose_name='inscrições até'),
        ),
    ]
