# Generated by Django 5.2.15 on 2026-08-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_evento_inscricoes_ate'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='valores',
            field=models.CharField(blank=True, help_text='valores possíveis da inscrição, separados por vírgula (ex.: 180, 260) — usados pra linkar receitas por valor', max_length=100, verbose_name='valores de inscrição'),
        ),
    ]
