# Generated by Django 5.2.15 on 2026-08-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_evento_valores'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='inscricoes_de',
            field=models.DateField(blank=True, help_text='abertura das inscrições — início da janela de reconhecimento de receitas', null=True, verbose_name='inscrições de'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='fim do torneio'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='início do torneio'),
        ),
    ]
