# Generated by Django 5.2.15 on 2026-08-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='nome')),
                ('player_id', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Player ID')),
                ('genero', models.CharField(blank=True, max_length=20, verbose_name='gênero')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('classe', models.CharField(blank=True, max_length=40, verbose_name='classe')),
                ('treinador', models.CharField(blank=True, max_length=120, verbose_name='treinador')),
                ('telefone', models.CharField(blank=True, max_length=40, verbose_name='telefone')),
                ('email', models.CharField(blank=True, max_length=160, verbose_name='e-mail')),
                ('regiao', models.CharField(blank=True, max_length=60, verbose_name='região')),
                ('filiacao', models.CharField(blank=True, max_length=40, verbose_name='filiação')),
                ('local1', models.CharField(blank=True, max_length=160, verbose_name='local 1')),
                ('local2', models.CharField(blank=True, max_length=160, verbose_name='local 2')),
                ('local3', models.CharField(blank=True, max_length=160, verbose_name='local 3')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'atleta',
                'verbose_name_plural': 'atletas',
                'ordering': ['nome'],
            },
        ),
    ]
