# Generated by Django 5.2.15 on 2026-08-08 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atleta_nome', models.CharField(max_length=160, verbose_name='atleta')),
                ('campeonato', models.CharField(max_length=160, verbose_name='campeonato')),
                ('data', models.DateField(blank=True, null=True, verbose_name='data')),
                ('categoria', models.CharField(blank=True, max_length=120, verbose_name='categoria disputada')),
                ('colocacao', models.CharField(blank=True, max_length=60, verbose_name='colocação')),
                ('pontuacao', models.IntegerField(blank=True, null=True, verbose_name='pontuação')),
                ('academia', models.CharField(blank=True, max_length=160, verbose_name='academia/clube')),
                ('treinador', models.CharField(blank=True, max_length=120, verbose_name='treinador')),
                ('atleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes', to='bases.atleta')),
            ],
            options={
                'verbose_name': 'participação',
                'verbose_name_plural': 'participações',
                'ordering': ['-data', 'campeonato', 'atleta_nome'],
                'indexes': [models.Index(fields=['campeonato'], name='bases_parti_campeon_073fa3_idx'), models.Index(fields=['atleta_nome'], name='bases_parti_atleta__7c39b6_idx')],
            },
        ),
    ]
