# Generated by Django 5.2.15 on 2026-06-10 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoVindi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vindi_id', models.BigIntegerField(unique=True, verbose_name='ID na Vindi')),
                ('nome', models.CharField(max_length=200, verbose_name='plano')),
                ('tipo', models.CharField(choices=[('filiacao', 'Filiação'), ('interior', 'Interior'), ('juvenil', 'Juvenil'), ('squashe', 'SquaSHE'), ('outros', 'Outros'), ('ignorar', 'Ignorar')], default='outros', max_length=20, verbose_name='tipo')),
                ('intervalo', models.CharField(blank=True, max_length=50, verbose_name='intervalo')),
                ('status', models.CharField(blank=True, max_length=30, verbose_name='status')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'plano (Vindi)',
                'verbose_name_plural': 'planos (Vindi)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaVindi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vindi_id', models.BigIntegerField(unique=True, verbose_name='ID na Vindi')),
                ('cliente_nome', models.CharField(max_length=200, verbose_name='nome')),
                ('cliente_vindi_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID do cliente na Vindi')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('cliente_documento', models.CharField(blank=True, max_length=30, verbose_name='documento (CPF)')),
                ('plano_nome', models.CharField(blank=True, max_length=200, verbose_name='plano')),
                ('tipo', models.CharField(choices=[('filiacao', 'Filiação'), ('interior', 'Interior'), ('juvenil', 'Juvenil'), ('squashe', 'SquaSHE'), ('outros', 'Outros'), ('ignorar', 'Ignorar')], default='outros', max_length=20, verbose_name='tipo')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='status')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='data de filiação')),
                ('proxima_cobranca', models.DateField(blank=True, null=True, verbose_name='próxima cobrança')),
                ('inadimplente_desde', models.DateField(blank=True, null=True, verbose_name='inadimplente desde')),
                ('cancelada_em', models.DateField(blank=True, null=True, verbose_name='cancelada em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas', to='assinaturas.planovindi')),
            ],
            options={
                'verbose_name': 'assinatura (Vindi)',
                'verbose_name_plural': 'assinaturas (Vindi)',
                'ordering': ['cliente_nome'],
            },
        ),
    ]
