# Generated by Django 5.2.15 on 2026-06-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecebimentoVindi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vindi_id', models.BigIntegerField(unique=True, verbose_name='ID na Vindi')),
                ('cliente_nome', models.CharField(max_length=200, verbose_name='nome')),
                ('cliente_vindi_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID do cliente na Vindi')),
                ('plano_nome', models.CharField(blank=True, max_length=200, verbose_name='plano')),
                ('tipo', models.CharField(choices=[('filiacao', 'Filiação'), ('interior', 'Interior'), ('juvenil', 'Juvenil'), ('squashe', 'SquaSHE'), ('outros', 'Outros'), ('ignorar', 'Ignorar')], default='outros', max_length=20, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor (R$)')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='status')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='data do pagamento')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'recebimento (Vindi)',
                'verbose_name_plural': 'recebimentos (Vindi)',
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
