# Generated by Django 5.2.15 on 2026-06-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0002_recebimentovindi'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturavindi',
            name='intervalo_meses',
            field=models.PositiveIntegerField(default=1, verbose_name='intervalo (meses)'),
        ),
        migrations.AddField(
            model_name='assinaturavindi',
            name='valor_ciclo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor por cobrança (R$)'),
        ),
    ]
