# Generated by Django 5.2.15 on 2026-08-08 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0003_assinaturavindi_intervalo_meses_and_more'),
        ('bases', '0002_participacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturavindi',
            name='atleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_vindi', to='bases.atleta', verbose_name='atleta (conciliação)'),
        ),
    ]
