# Generated by Django 5.2.15 on 2026-06-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='lançamento')),
                ('razao_social', models.CharField(blank=True, max_length=255, verbose_name='razão social')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=30, verbose_name='CPF/CNPJ')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor (R$)')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10, verbose_name='tipo')),
                ('grupo', models.CharField(blank=True, max_length=40, verbose_name='grupo')),
                ('categoria', models.CharField(blank=True, max_length=80, verbose_name='categoria')),
                ('evento', models.CharField(blank=True, max_length=120, verbose_name='evento')),
                ('classificado', models.BooleanField(default=False, verbose_name='classificado')),
                ('importado_em', models.DateTimeField(auto_now_add=True, verbose_name='importado em')),
            ],
            options={
                'verbose_name': 'lançamento bancário',
                'verbose_name_plural': 'lançamentos bancários',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
