# Generated by Django 5.2.15 on 2026-06-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentobancario',
            name='revisado',
            field=models.BooleanField(default=False, help_text='Marque para preservar esta classificação ao reimportar o extrato.', verbose_name='revisado manualmente'),
        ),
        migrations.AlterField(
            model_name='lancamentobancario',
            name='grupo',
            field=models.CharField(blank=True, choices=[('Torneios', 'Torneios'), ('Folha', 'Folha'), ('Despesas gerais', 'Despesas gerais'), ('Patrocínios', 'Patrocínios'), ('Inscrições', 'Inscrições'), ('SquaSHE', 'SquaSHE'), ('Cartão/Vindi', 'Cartão/Vindi'), ('Filiação', 'Filiação'), ('Outras receitas', 'Outras receitas'), ('Financeiro (não operacional)', 'Financeiro (não operacional)')], max_length=40, verbose_name='grupo'),
        ),
    ]
