# Generated by Django 5.2.15 on 2026-06-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_lancamentobancario_revisado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(default=2026, verbose_name='ano')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='mês')),
                ('data', models.DateField(blank=True, null=True, verbose_name='data')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10, verbose_name='tipo')),
                ('grupo', models.CharField(max_length=40, verbose_name='grupo')),
                ('categoria', models.CharField(blank=True, max_length=80, verbose_name='categoria')),
                ('evento', models.CharField(blank=True, max_length=120, verbose_name='evento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor (R$)')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('origem', models.CharField(choices=[('planilha', 'Planilha (até maio)'), ('extrato', 'Extrato bancário')], default='planilha', max_length=12, verbose_name='origem')),
                ('pago', models.BooleanField(default=True, verbose_name='pago')),
            ],
            options={
                'verbose_name': 'lançamento financeiro',
                'verbose_name_plural': 'lançamentos financeiros',
                'ordering': ['ano', 'mes', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='lancamentobancario',
            name='grupo',
            field=models.CharField(blank=True, choices=[('Torneios', 'Torneios'), ('Folha', 'Folha'), ('Despesas gerais', 'Despesas gerais'), ('Patrocínios', 'Patrocínios'), ('Inscrições', 'Inscrições'), ('SquaSHE', 'SquaSHE'), ('Cartão/Vindi', 'Cartão/Vindi'), ('Filiação', 'Filiação'), ('Receitas', 'Receitas'), ('Outras receitas', 'Outras receitas'), ('Financeiro (não operacional)', 'Financeiro (não operacional)')], max_length=40, verbose_name='grupo'),
        ),
    ]
