# Generated by Django 5.2.15 on 2026-07-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_lancamentofinanceiro_alter_lancamentobancario_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPrevisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], default='despesa', max_length=10, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor (R$)')),
                ('recorrencia', models.CharField(choices=[('mensal', 'Todo mês'), ('anual', 'Uma vez por ano'), ('unico', 'Único (mês específico)')], default='mensal', max_length=10, verbose_name='recorrência')),
                ('mes', models.PositiveSmallIntegerField(blank=True, help_text='Para anual/único: mês em que ocorre (1–12). Mensal: deixe em branco.', null=True, verbose_name='mês')),
                ('categoria', models.CharField(blank=True, max_length=80, verbose_name='categoria')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='observação')),
            ],
            options={
                'verbose_name': 'item de previsão',
                'verbose_name_plural': 'itens de previsão',
                'ordering': ['tipo', '-valor'],
            },
        ),
    ]
