# Generated by Django 5.2.15 on 2026-07-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_itemprevisao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=120, verbose_name='evento')),
                ('ano', models.PositiveSmallIntegerField(default=2026, verbose_name='ano')),
                ('nome', models.CharField(max_length=160, verbose_name='atleta')),
                ('email', models.CharField(blank=True, max_length=160, verbose_name='e-mail')),
                ('clube', models.CharField(blank=True, max_length=160, verbose_name='clube/academia')),
                ('treinador', models.CharField(blank=True, max_length=160, verbose_name='treinador')),
                ('categoria', models.CharField(blank=True, max_length=80, verbose_name='categoria')),
                ('filiado', models.CharField(blank=True, max_length=20, verbose_name='filiado')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor (R$)')),
                ('comprovante_link', models.CharField(blank=True, max_length=500, verbose_name='comprovante (link)')),
                ('pacote', models.BooleanField(default=False, verbose_name='pagou via pacote')),
                ('data_inscricao', models.DateField(blank=True, null=True, verbose_name='data da inscrição')),
                ('importado_em', models.DateTimeField(auto_now_add=True, verbose_name='importado em')),
            ],
            options={
                'verbose_name': 'inscrição',
                'verbose_name_plural': 'inscrições',
                'ordering': ['evento', 'nome'],
            },
        ),
    ]
